image: "python:3.8"

before_script:
  - python --version

after_script:
  - docker-compose down -v

stages:
  - lint
  - build
  - security
  - test


lint:
  stage: lint
  before_script:
    - pip3 install flake8
  script:
  - flake8 .
  allow_failure: true

.anchore_scan:
  image: anchore/engine-cli:latest
  stage: security
  tags:
    - docker-privileged
  variables:
    # Configure for recursive submodule cloning
    GIT_SUBMODULE_STRATEGY: recursive

package:security:
  stage: build
  before_script:
    - pip3 install safety
    - wget https://github.com/pyupio/safety-db/raw/master/data/insecure_full.json
    - wget https://github.com/pyupio/safety-db/raw/master/data/insecure.json
  script:
    - safety check --full-report --db . -r requirements/base.txt
    - safety check --full-report --db . -r requirements/dev.txt

services:
  - docker:dind

test:unit:
  stage: test
  image: hmajid2301/dind-docker-compose
  script:
    - docker-compose -f docker-compose.dev.yaml up --build --exit-code-from test test db | grep -v "django.db.backends.schema\|faker.factory\|MOD schema\|MOD factory\|bad news\|autovacuum process"
  after_script:
    - docker-compose -f docker-compose.dev.yaml down -v
