version: '3.8'

services:
  db:
    image: postgres:16.0-alpine
    container_name: db
    expose:
     - 5432
    volumes:
      - mainapps_pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      mainappsnetwork:
  
  apps:
    image: mainapps:latest
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mainapps
    volumes:
      - mainapps_static_volume:/mainapps/files/static-collected
      - mainapps_media_volume:/mainapps/files/media
    env_file:
      - .env
    expose:
      - 8001
    networks:
      mainappsnetwork:
  
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - mainapps_static_volume:/mainapps/files/static-collected
      - mainapps_media_volume:/mainapps/files/media
      - .:/nginx/etc/nginx/conf.d/
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - apps
    networks:
      mainappsnetwork:

volumes:
  mainapps_static_volume:
  mainapps_media_volume:
  mainapps_pg_data:

networks:
  mainappsnetwork: